### ISSUE TITLE
Votação Logo ABC Dev!

### ISSUE THREAD

**Issue by woliveiras** [femug-abc/femug-abc#11]
Aberto para votação dos logos [enviados](https://github.com/femug-abc/femug-abc/issues/8).

Basta deixar um comentário com o número do logo mais interessante.

**Ex.: 7**
#1 ------------------------------------------------------------

![](https://cloud.githubusercontent.com/assets/4243601/12694704/bc27094c-c71d-11e5-853c-cc1d6538ff06.png)
#2 ------------------------------------------------------------

![](https://cloud.githubusercontent.com/assets/4243601/12694705/c97be388-c71d-11e5-8d2b-e28ac7612b3f.png)
#3 ------------------------------------------------------------

![](https://cloud.githubusercontent.com/assets/4243601/12696743/6325efca-c759-11e5-8247-1b5301799b8f.png)
#4 ------------------------------------------------------------

![](https://cloud.githubusercontent.com/assets/4243601/12696744/64db0e36-c759-11e5-8798-6142e28c6a18.png)
#5 ------------------------------------------------------------

![](https://cloud.githubusercontent.com/assets/4243601/12706139/714bd4c2-c865-11e5-9549-312b192c7069.png)
#6 ------------------------------------------------------------

![](https://cloud.githubusercontent.com/assets/4243601/12706140/7154debe-c865-11e5-9705-1cee79e162f5.png)
#7 ------------------------------------------------------------

![](https://cloud.githubusercontent.com/assets/4243601/12726983/c652c3a8-c901-11e5-9ba6-ab9f73053f37.jpg)

**Comment by Lithinho** [comment]
5

**Comment by akfzambrana** [comment]
7 opção 2

**Comment by danilopimenta** [comment]
6

**Comment by woliveiras** [comment]
7, as duas opções ficaram fodas! - Difícil escolha gente... :(

**Comment by pedrosd92** [comment]
7 opção 2 com uma observação.

1 - Muda a fonte do bloco DEV, para diferenciar o ABC do DEV.("ABCDEV" tudo junto parece o alfabeto com 1 letra errada xD)
2 - O "<>" poderia ter a arte triangular(ou poly art) do primeiro Logo.

**Comment by maugravena** [comment]
7

**Comment by ubirajarapelli** [comment]
Eu voto no meu: **1**

**Comment by fbadaro** [comment]
7 Opção 1, acho que a tipografia do mesmo tamanho fica melhor!

**Comment by victorkurauchi** [comment]
1

**Comment by marquinhusgoncalves-zz** [comment]
**Opção: 7**

**Comment by feraio** [comment]
1

**Comment by tamihh** [comment]
7 opção 2

**Comment by willianribeiro** [comment]
7 opção 2

**Comment by woliveiras** [comment]
Proposta de logo 7, opção 2 ganhou galera.

**Comment by woliveiras** [comment]
Proposta de logo 7, opção 2 ganhou galera.
